version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: egrex-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bienestar}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-CAMILO129}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    volumes:
      - egrex_postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data

  backend:
    image: camilo129/egrex-backend:latest
    container_name: egrex-backend
    restart: always
    # Puertos expuestos si es necesario acceder directamente al API
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - data
      - ingress

  frontend:
    image: camilo129/egrex-frontend:latest
    container_name: egrex-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ingress

networks:
  data:
    driver: bridge
  ingress:
    driver: bridge

volumes:
  egrex_postgres_data_prod:
    driver: local
